{% set name = "aicssegmentation" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aicssegmentation-{{ version }}.tar.gz
  sha256: b9d7a8f4a84177e776653248bd5343e37856d5bbeba75d3fdf34774bc586c318

build:
  entry_points:
    - batch_processing=aicssegmentation.bin.batch_processing:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - pytest-runner >=5.2
    - python {{ python_min }}
  run:
    - aicsimageio >=4.0.5
    - dask-core
    - itk
    - itkwidgets
    - jupyter
    - matplotlib-base
    - napari
    - numpy >=1.15.1
    - pandas >=0.23.4
    - python >={{ python_min }}
    - scikit-image
    - scipy >=1.1.0

test:
  imports:
    - aicssegmentation
  commands:
    - pip list
    # - pip check
    - batch_processing --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/aicssegmentation
  summary: Part 1 of Allen Cell and Structure Segmenter
  license: BSD-2-Clause
  license_file: LICENSE
  dev_url: https://github.com/AllenCell/aicssegmentation

extra:
  recipe-maintainers:
    - goanpeca
    - jxchen01
